### ISSUE TITLE
Bounce not processed if VERP Localpart configured

### ISSUE THREAD

**Issue by mjwright** [mecachisenros/com.github.ses#3]
Function get_verp_items() does not account for Localpart if configured in CiviMail account settings, and bounce processing will fail if present.

CRM/Ses/Page/Webhook.php::get_verp_items() should be something like this:

```php
protected function get_verp_items( $header_value ) {
	$localpart = CRM_Core_BAO_MailSettings::defaultLocalpart();
	$verp_items = substr( substr( $header_value, 0, strpos( $header_value, '@' ) ), sizeof( $localpart ) + 2 );
	return explode( $this->verp_separator, $verp_items );
}
```

**Comment by mecachisenros** [comment]
@mjwright thank you for reporting, the referenced commit fixes the issue.
