### ISSUE TITLE
SNS configuration question

### ISSUE THREAD

**Issue by cdhassell** [mecachisenros/com.github.ses#5]
The SNS "create subscription" page asks for the protocol of the endpoint.  I'm unsure whether the correct answer is "HTTPS" or "Platform application endpoint".  Can you clarify?  Thanks.

**Comment by cdhassell** [comment]
Just to close this out, it appears that HTTPS is the correct choice.  I tried it both with and without the raw message checkbox, and it didn't seem to matter.  I will try to put together a step by step setup tutorial, in case that is helpful to others.

**Comment by narthur** [comment]
Have you been able to put together that tutorial yet, @cdhassell ?

**Comment by cdhassell** [comment]
No, because I was never able to make this extension work properly despite many tries.  I gave up and dropped back to simply using SNS to forward the bounced emails to a dedicated email account for Civicrm to pick up and process.  The out-of-the-box functionality on this works fine.
